spring:
  profiles:
    active:
    - dev

---
spring:
  profiles: dev # 开发环境
  application:
    name: microservice-awake-config-dev
    admin:
      jmx-name:

---
spring:
  profiles: test #测试环境
  application:
    name: microservice-awake-config-test